config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  root controller: :articles, action: :index
  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    validates :title, presence: true,
                      length: { minimum: 5 }
    validates :content, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
    validates :views, presence: true
    validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ }, allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
    @articles = Article.all
  end
  
  def show
    @article = Article.find(params[:id])
  end
  
  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def create
    @article = Article.new(article_params)
    
    if @article.save
      redirect_to @article
      flash[:notice] = "Article was successfully created."
    else
      flash[:notice] = "Please fill in the form."
      render :new
    end  
  
  end

  private

  def article_params
    params[:article].permit(:title, :content)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create

        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        
        if @comment.save
            redirect_to article_path(@article)
            flash[:notice] = "Comment was successfully created."
        else
            redirect_to article_path(@article)
            flash[:notice] = "Please provide a comment."
        end  
    end
    
    private
    def comment_params
        params.require(:comment).permit(:email, :views)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h2>Edit Article Form</h2>

<%= form_with model: @article, url: article_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <p><%= article.title %></p>
  <p><%= article.content %></p>
  <%= link_to 'Edit Article', edit_article_path(article)%>
  <%= link_to 'Show', article_path(article) %>
<% end %>

app/views/articles/new.html.erb
<h2>New Article Form</h2>

<%= form_with model: @article, url: articles_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/articles/show.html.erb
<p><%= @article.title %></p>
<p><%= @article.content %></p>

<h2>Comments</h2>
<% @article.comments.each do |comment| %>
    <p>
        <strong>Comment:</strong>
        <%= comment.views %>
    </p>
    <p>
        <strong>Email:</strong>
        <%= comment.email %>
    </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
    <p>
        <%= form.label :views %><br>
        <%= form.text_area :views %>
    </p>
    <p>
        <%= form.label :email %><br>
        <%= form.text_field :email %>
    </p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Home", root_path%>
    <%= link_to "New Article", new_article_url%>
    <%flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <%end %>
    <%= yield %>
  </body>
</html>